name: bananna
favicon: null
layout_spectrum: 0.8376582213677466
typography_spectrum: 0.47687576385214925
title: Bananna Website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.03659385954961181
  lightness: 0.7525675636716187
  saturation: 0.6026057575363666
  rhythmicContrast: 0.5214219789486378
purpose: []
